zip-creator: update

diff --git a/zip-creator/base/META-INF/com/google/android/update-binary b/zip-creator/base/META-INF/com/google/android/update-binary
--- a/zip-creator/base/META-INF/com/google/android/update-binary
+++ b/zip-creator/base/META-INF/com/google/android/update-binary
@@ -63,9 +63,56 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.devicecheck)" == 1 ]; then
   fi;
 fi;
 
-ui_print "";
-ui_print "Kernel for MotoG2 Titan-Thea";
-ui_print "";
+if [ "$3" ]; then
+	zip=$3
+	console=/proc/$$/fd/$2
+	# write the location of the console buffer to /tmp/console for other scripts to use
+	echo "$console" > /tmp/console
+else
+	console=$(cat /tmp/console)
+	[ "$console" ] || console=/proc/$$/fd/1
+fi
+
+print() {
+	if [ "$1" ]; then
+		echo "ui_print $1" > "$console"
+	else
+		echo "ui_print  " > "$console"
+	fi
+	echo
+}
+
+abort() {
+	[ "$1" ] && {
+		print "Error: $1"
+		print "Aborting..."
+	}
+	print "Failed to patch boot image!"
+}
+
+cleanup() {
+	[ "$zip" ] && rm /tmp/console
+	umount /system
+}
+
+extract() {
+	rm -rf "$2"
+	mkdir -p "$2"
+	unzip -o "$1" -d "$2" || abort "Failed to extract zip to $2!"
+}
+
+setperm() {
+	find "$3" -type d -exec chmod "$1" {} \;
+	find "$3" -type f -exec chmod "$2" {} \;
+}
+
+ui_print " ";
+ui_print " ";
+ui_print "============================================";
+ui_print "                FLOPPY KERNEL               ";
+ui_print "============================================";
+ui_print " ";
+ui_print " ";
 ui_print " ";
 ui_print "by JonasCardoso";
 ui_print " ";
